/** Adapted from https://github.com/jtlapp/kysely-test-sync/blob/main/test/mock-kysely-files/subdir/local-4.ts */

/* BEGIN COPIED CODE */
export const A4_different = 1;
export const B4 = 2;
export const C4_different = 3;
export const D4 = 4;
/* END COPIED CODE */
/* BEGIN COPIED CODE */
export const E4_different = 5;
export const F4 = 6;
/* END COPIED CODE */
/* BEGIN COPIED CODE */
export const G4 = 7;
export const H4 = 8;
/* END COPIED CODE */
/* BEGIN COPIED CODE */
export const I4 = 9;
export const J4_different = 10;
/* END COPIED CODE */
