/* SYNC WITH https://raw.githubusercontent.com/jtlapp/kysely-test-sync/main/test/mock-kysely-files/kysely-2.ts */
export const A2x = 1;
/* BEGIN SYNCED CODE */
export const B2 = 2;
export const C2 = 3;
/* END SYNCED CODE */
export const D2x = 4;
export const E2x = 5;
export const F2x = 6;
/* BEGIN SYNCED CODE */
export const G2 = 7;
export const H2 = 8;
export const I2 = 9;
export const J2 = 10;
/* END SYNCED CODE */
